#!/usr/bin/env bash
#
# One-time (and idempotent) local setup. Safe to re-run.
#   - writes wordpress/wp-config.php if missing
#   - starts the Docker stack
#   - repairs MySQL performance_schema (so mysqldump works)
#   - installs + builds the theme with the pinned Node
#   - registers the portless route -> https://kcnb1-france.localhost
#
# Run `scripts/sync-from-prod.sh` afterwards to fill the DB + uploads with prod data.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_config.sh"
cd "$ROOT"

step() { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }

# --- wp-config.php ---------------------------------------------------------
if [ -f wordpress/wp-config.php ]; then
  step "wp-config.php already present, leaving it untouched"
else
  step "Writing wordpress/wp-config.php"
  SALTS="$(curl -fsS https://api.wordpress.org/secret-key/1.1/salt/ 2>/dev/null || true)"
  if [ -z "$SALTS" ]; then
    # Offline fallback: generate 8 random salts locally.
    keys=(AUTH_KEY SECURE_AUTH_KEY LOGGED_IN_KEY NONCE_KEY AUTH_SALT SECURE_AUTH_SALT LOGGED_IN_SALT NONCE_SALT)
    SALTS=""
    for k in "${keys[@]}"; do
      v="$(openssl rand -base64 48 | tr -d '\n')"
      SALTS+="define('${k}', '${v}');"$'\n'
    done
  fi
  cat > wordpress/wp-config.php <<PHP
<?php
/**
 * Local development config for the Docker stack, fronted by portless.
 * Generated by scripts/setup.sh. This file is gitignored.
 */

// Behind the portless HTTPS proxy: trust the forwarded host/proto so WordPress
// builds canonical URLs against ${LOCAL_HOST} instead of the 127.0.0.1 upstream.
if (!empty(\$_SERVER['HTTP_X_FORWARDED_HOST'])) {
    \$_SERVER['HTTP_HOST'] = \$_SERVER['HTTP_X_FORWARDED_HOST'];
}
if ((\$_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https') {
    \$_SERVER['HTTPS'] = 'on';
}

// ** MySQL settings (from docker-compose.yml \`db\` service) ** //
define('DB_NAME', 'wordpress');
define('DB_USER', 'root');
define('DB_PASSWORD', 'password');
define('DB_HOST', 'db');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

define('WP_HOME', '${LOCAL_URL}');
define('WP_SITEURL', '${LOCAL_URL}');

${SALTS}
\$table_prefix = 'wp_';

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

require_once(ABSPATH . 'wp-settings.php');
PHP
fi

# --- Docker ----------------------------------------------------------------
step "Starting Docker stack"
docker compose up -d

step "Waiting for MySQL to be ready"
for _ in $(seq 1 60); do
  if db_mysql -e 'SELECT 1' >/dev/null 2>&1; then break; fi
  sleep 1
done

step "Repairing performance_schema (makes mysqldump work)"
db mysql_upgrade -u root -ppassword >/dev/null 2>&1 || true

# --- Theme build -----------------------------------------------------------
step "Building the theme with Node ${NODE_VERSION}"
run_node() {
  if command -v fnm >/dev/null 2>&1; then
    fnm install "$NODE_VERSION" >/dev/null 2>&1 || true
    fnm exec --using="$NODE_VERSION" "$@"
  else
    echo "  (fnm not found, using system node $(node -v 2>/dev/null))"
    "$@"
  fi
}
( cd "$THEME_DIR"
  if [ ! -d node_modules ]; then run_node npm ci; fi
  run_node npm run build
)

# --- portless --------------------------------------------------------------
step "Registering portless route ${PORTLESS_NAME} -> ${NGINX_PORT}"
if portless_cmd alias "$PORTLESS_NAME" "$NGINX_PORT"; then
  :
else
  echo "  Could not run portless automatically. Run this once yourself:"
  echo "    portless alias ${PORTLESS_NAME} ${NGINX_PORT}"
fi

# --- Done ------------------------------------------------------------------
step "Done"
echo "Open ${LOCAL_URL}"
if [ "$(db_mysql -N -e "SELECT COUNT(*) FROM wordpress.wp_posts" 2>/dev/null || echo 0)" -lt 5 ]; then
  echo "The database looks empty. Pull production data with:"
  echo "    scripts/sync-from-prod.sh"
fi
